# This is the config file for building NGS and running its gtest suite
# with Travis-ci.org

matrix:
  fast_finish: true
  include:
    # - os: linux
    #   compiler: gcc
    #   language: cpp
    #   sudo: required
    #   cache:
    #     apt: true
    #     directories:
    #       - $HOME/.ccache
    #   env:
    #     - BUILD_NAME=gcc52_stdcpp14_sanitize
    #     - DETAILS=""
    - os: linux
      compiler: gcc
      language: cpp
      dist: trusty
      sudo: required
      env:
        - BUILD_NAME=linux_gcc
        - DETAILS=""
    - os: linux
      compiler: clang
      language: cpp
      dist: trusty
      sudo: required
      env:
        - BUILD_NAME=linux_clang
        - DETAILS=""
    - osx_image: xcode8.3
      language: objective-c
      compiler: clang
      env:
        - BUILD_NAME=osx
        - DETAILS=""
    - os: linux
      compiler: gcc
      language: cpp
      sudo: true
      dist: trusty
      cache:
    #    apt: true
        directories:
    #      - $HOME/.ccache
          - $HOME/downloads
      env:
        - BUILD_NAME=android
        - DETAILS=""
    # - os: linux
    #   compiler: clang
    #   language: cpp
    #   sudo: true
    #   dist: trusty
    #   cache:
    # #    apt: true
    #     directories:
    # #      - $HOME/.ccache
    #       - $HOME/downloads
    #   env:
    #     - BUILD_NAME=android_cmake
    #     - DETAILS=""

install:
  - ./ci/travis/${BUILD_NAME}/install.sh

script:
  - ./ci/travis/${BUILD_NAME}/script.sh

notifications:
  email:
    recipients:
      - dmitry.baryshnikov@nextgis.com
